config/routes.rb
Rails.application.routes.draw do

  concern :paginatable do
    get '(page/:page)', action: :index, on: :collection, as: ''
  end

  devise_for :users, controllers: {
    registrations: "user_registrations",
    confirmations: "user_confirmations",
    sessions: "user_sessions",
    passwords: "user_passwords"
  }

  devise_scope :user do
    get "/users/reset_password_link_sent" => "user_passwords#reset_password_link_sent", as: :reset_password_link_sent
  end

  root 'static_pages#home'

  # Static pages
  get 'welcome' => 'static_pages#sign_up_success', as: :sign_up_success
  get 'sign_up_unconfirmed' => 'static_pages#sign_up_unconfirmed', as: :sign_up_unconfirmed
  get 'myprofile' => 'static_pages#my_profile', as: :my_profile
  get 'en/product-overview' => 'static_pages#product_overview', as: :product_overview
  get 'en/privacy-policy' => 'static_pages#privacy_policy', as: :privacy_policy
  get 'en/terms-of-service' => 'static_pages#terms_of_service', as: :terms_of_service

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/shared/_create.js.erb
<% model_name = object.class.to_s.underscore %>
<% inserter ||= "function(content) {$(content).prependTo('##{model_name}s-list')}" %>

<%# Sometimes, the table-head has class hidden if the list was empty before. Removing this class now: %>
$('.<%= model_name %>-table-head').removeClass('hidden');

(<%= inserter.html_safe %>)("<%= escape_javascript(render 'list_item_wrapper', model_name.to_sym => object) %>");

<% if close_modal %>
  $("#new-<%= model_name %>-form").modal('toggle');
<% end %>

$("#<%= model_name %>s-empty-message").remove();

<%= render 'shared/reload_flash' %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% object.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/shared/_field_error.html.erb
<% if error_messages.any? %>
  <%= field_name %> <%= error_messages.join(', ') %>
<% end %>

app/views/shared/_form.js.erb
<% model_name = object.class.to_s.underscore %>
<% form_id = "#{action}-#{model_name}-form" %>

<%= render 'shared/modal', modal_id: form_id, body: escape_javascript(render 'form',
  model_name.to_sym => object,
  submit_button_name: _('Save %s') % model_name,
  remote: true) %>

app/views/shared/_home.html.erb
<% sign_up_link = _("Register") %>
<% sign_in_link = _("Sign in") %>
<% forgot_password_link = _("Forgot your password?") %>

<div class="homepage-container">
  <div class="head">
    <!-- <div class="space"></div> -->
    <div class="logo">
      <%= inline_svg("Entypo+/solid-heart.svg", class: "logo-icon filled", title: "swsw") %>
    </div>
  </div>

  <div class="body-container">
    <div class="body">
      <!-- <div class="box"></div>
      <div class="space"></div> -->
      <div class="content">
        <p class="cta">
          <%= link_to sign_up_link, new_user_registration_path, remote: true, class: "button" %>
          <%= _("or") %>
          <%= link_to sign_in_link, new_user_session_path, remote: true %>
        </p>
        <p class="small">
          <%= link_to forgot_password_link, new_user_password_path, remote: true %>
        </p>
      </div>
    </div>
  </div>

  <div class="footer">
    <%= link_to _("Product overview"), product_overview_path %>
    <div class="space"></div>
    <%= link_to _("Terms of service"), terms_of_service_path %>
    <div class="space"></div>
    <%= link_to _("Privacy policy"), privacy_policy_path %>
  </div>
</div>

<%# MODALS %>
<%= render 'shared/modal', modal_id: "new_user_registration", modal_title: _("Create account"), css_class: 'small hundred' %>
<%= render 'shared/modal', modal_id: "new_user_session", modal_title: "", css_class: 'small hundred' %>
<%= render 'shared/modal', modal_id: "large", modal_title: "", css_class: 'hundred', dialog_css_class: 'modal-lg' %>

app/views/shared/_modal.html.erb
<% body ||= '<span class="glyphicon glyphicon-refresh spin"></span>' %>
<div class="modal fade<%= ' ' + css_class if defined?(css_class) %>" id="<%= modal_id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog <%= dialog_css_class if defined?(dialog_css_class) %>" role="document">
    <div class="modal-content">
      <div class='modal-header'>
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true" aria-label="Close">&times;</button>
        <h3 class="modal-title"><%= modal_title %></h3>
      </div>
      <div class="modal-body">
        <%= body %>
      </div>
      <%#
        <div class='modal-footer'>
          <button type="button" data-dismiss="modal" class="btn">
            %= _("Close") %
          </button>
        </div>
      %>
    </div>
  </div>
</div>

app/views/shared/_modal.js.erb
<%# Inject the given body-html into the modal body %>
$('#<%= modal_id %> .modal-body').html("<%= body %>");

<%# Change modal title, if a title is given %>
<% if defined?(title) %>
  $('#<%= modal_id %> .modal-title').html("<%= title %>");
<% end %>

var afterShow = function () {
  $('#<%= modal_id %> input.form-control:first').focus();
  Combos.injectToPage('#<%= modal_id %>');
  Cocoon.processPage('#<%= modal_id %>');
  Icheck.injectToPage('#<%= modal_id %>');
};

if ($('#<%= modal_id %>').is(":visible")) {
  afterShow();
} else {
  <%# Open the modal %>
  $('#<%= modal_id %>').modal().on('shown.bs.modal', afterShow);
}

app/views/shared/_modal_form_buttons.html.erb
<% submit_label ||= _("Save") %>

<div class="actions form-group">
  <%= f.submit submit_label, class: "btn btn-block" %>
  <%= link_to _("Cancel"), 'javascript:void(0)', 'data-dismiss' => 'modal', class: "btn btn-block btn-hollow" %>
</div>

app/views/shared/_reload_flash.js.erb
$("#flash").html("<%= escape_javascript(render 'layouts/flash') %>");

app/views/shared/_update.js.erb
<% model_name = object.class.to_s.underscore %>
<% list_item_selector ||= "##{model_name}-list-item-#{object.id}" %>

$('<%= list_item_selector %>').
  html("<%= escape_javascript(render 'list_item', model_name.to_sym => object) %>");

$("#edit-<%= model_name %>-form").modal('toggle');

<%= render 'shared/reload_flash' %>