config/routes.rb
Rails.application.routes.draw do

  concern :paginatable do
    get '(page/:page)', action: :index, on: :collection, as: ''
  end

  devise_for :users, controllers: {
    registrations: "user_registrations",
    confirmations: "user_confirmations",
    sessions: "user_sessions",
    passwords: "user_passwords"
  }

  devise_scope :user do
    get "/users/reset_password_link_sent" => "user_passwords#reset_password_link_sent", as: :reset_password_link_sent
  end

  root 'static_pages#home'

  # Static pages
  get 'welcome' => 'static_pages#sign_up_success', as: :sign_up_success
  get 'sign_up_unconfirmed' => 'static_pages#sign_up_unconfirmed', as: :sign_up_unconfirmed
  get 'myprofile' => 'static_pages#my_profile', as: :my_profile
  get 'en/product-overview' => 'static_pages#product_overview', as: :product_overview
  get 'en/privacy-policy' => 'static_pages#privacy_policy', as: :privacy_policy
  get 'en/terms-of-service' => 'static_pages#terms_of_service', as: :terms_of_service

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/layouts/_flash.html.erb
<% flash.each do |name, msg| -%>
  <%= content_tag :div, msg, class: "flash #{name}" %>
  <script type="text/javascript">growl("<%= name.capitalize %>", "<%= msg %>")</script>
<% end -%>

app/views/layouts/_header.html.erb
<% header_class_addition = yield(:css_schema) && yield(:css_schema).length > 0 ? " #{yield(:css_schema)}" : "" %>

<header class="main-header<%= header_class_addition %>">
  <div class="content">
    <div class="my-account">
      <%= _("My account") %>
      <%= inline_svg("Entypo+/chevron-down.svg", class: "icon") %>
      <div class="my-account-block">
        <ul>
          <li><%= link_to _("Settings"), my_profile_path %></li>
          <li>
            <%= form_tag destroy_user_session_path, method: :delete do %>
              <%= button_tag _("Sign out"), class: "link" %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</header>

app/views/layouts/_html_head.html.erb
<head>
  <title><%= page_title(yield(:title)) %></title>
  <%= render 'layouts/rollbar_js' if ENV['ROLLBAR_POST_CLIENT_ITEM_TOKEN'] %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_pack_tag 'application' %>
  <%= stylesheet_pack_tag 'application' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

app/views/layouts/_menu_item.html.erb
<% method = local_assigns[:method].nil? ? :get : local_assigns[:method] %>

<li class="menu-item <%= menu_link_class_for_path(path) %>">

  <%= link_to path, method: method do %>
    <div class="sidebar-icon-container">
      <%= inline_svg("Entypo+/#{icon}.svg", class: "sidebar-icon #{icon}") unless local_assigns[:icon].nil? %>
    </div>
    <div class="sidebar-text-container">
      <%= name %>
    </div>
  <% end %>
</li>

app/views/layouts/additional_costs.html.erb
<% provide(:title, _("Additional costs")) %>
<% provide(:css_schema, "yellow") %>
<% provide(:icon, "plus") %>

<%= render template: "layouts/application" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<%= render 'layouts/html_head' %>

<body>

<div class="wrapper">
  <%= render 'layouts/header' if user_signed_in? %>

  <div class="main-container">
    <div class="main-content">
      <div id="flash">
        <%= render 'layouts/flash' %>
      </div>
      <%= yield %>
    </div>
  </div>
</div>

</body>
</html>

app/views/layouts/blank.html.erb
<!DOCTYPE html>
<html>
<%= render 'layouts/html_head' %>

<body>

<div class="container-fluid">
  <div class="text-content">
    <div id="flash">
      <%= render 'layouts/flash' %>
    </div>
    <%= yield %>
  </div>
</div>

</body>
</html>

app/views/layouts/budgets.html.erb
<% provide(:title, _("Budget")) %>
<% provide(:css_schema, "blue") %>
<% provide(:icon, "wallet") %>

<%= render template: "layouts/application" %>

app/views/layouts/foods.html.erb
<% provide(:title, _("Food and drinks")) %>
<% provide(:css_schema, "purple") %>
<% provide(:icon, "drink") %>

<%= render template: "layouts/application" %>

app/views/layouts/guest_sets.html.erb
<% provide(:title, _("Guest list")) %>
<% provide(:css_schema, "green") %>
<% provide(:icon, "users") %>

<%= render template: "layouts/application" %>

app/views/layouts/locations.html.erb
<% provide(:title, _("Locations")) %>
<% provide(:css_schema, "orange") %>
<% provide(:icon, "location-pin") %>

<%= render template: "layouts/application" %>

app/views/layouts/officiants.html.erb
<% provide(:title, _("Officiants")) %>
<% provide(:css_schema, "red") %>
<% provide(:icon, "open-book") %>

<%= render template: "layouts/application" %>